### ISSUE TITLE
Can't seem to deploy

### ISSUE THREAD

**Issue by jerroldwee** [kengz/telegram-bot-bootstrap#1] opened 2015-10-29 14:10 UTC
Hello kengz. I've forked the file directly into my git account and deployed it. However, it throws an application error. The codes are uncommented and .env edited.

My fork can be viewed here. I can't seem to find what's wrong.

https://github.com/jerroldwee/waterflowz

**Comment by kengz** [comment] 2015-11-02 16:07
Hey there; I haven't deployed it for a while since I switched to [jarvis on Slack](https://github.com/kengz/jarvis) (if you wanna check it out!)

About this issue, can you attach the error log so I can see what's up?

**Comment by kengz** [comment] 2016-03-17 02:53
Closing for now until more cases are confirmed.

**Closed by kengz** 2016-03-17 02:53 UTC
